[package]
name = "rslogo"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["logolang_lib"]

[dependencies]
logolang_lib = { path = "logolang_lib"}
clap = { version = "4.4.4", features = ["derive"] }
nom = "=7.1.3"
unsvg = "1.1.1"
