[package]
name = "logolang_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unsvg = "1.1.1"
thiserror = "1.0.58"
anyhow = "1.0.81"
